### ISSUE TITLE
What parameters are trainable in the Similarity-based Self-matching module?

### ISSUE THREAD

**Issue by tqwei05** [ChenJiayi68/DMTNet#2]
Thank you for your great work!

I have a concern regarding the paper. It states that the Similarity-based Self-matching module is trainable and is optimized using the L1 loss. However, since both Fls and Flq are outputs of a frozen feature extractor, followed by masked pooling and averaging operations, I think it is more like a training-free module.

**Comment by ChenJiayi68** [comment]
Hi! : )
M1L is used as additional supervised information to optimize the later Adaptive Feature Transformation module through L1 loss.
