### ISSUE TITLE
About SMT

### ISSUE THREAD

**Issue by King-king424** [ChenJiayi68/DMTNet#4]
![image](https://github.com/user-attachments/assets/88ebe5e1-8add-4327-811a-1533d463c15a)

There seems to be no learnable parameters here.
The inputs are all features extracted from the frozen backbone.
So, the loss function here seems to have no effect.

**Comment by ChenJiayi68** [comment]
M1L is used as additional supervised information to optimize the later Adaptive Feature Transformation module through L1 loss. And the M1l obtained this way will be more accurate.
